export struct DnsProfileRow {
    id: string,
    name: string,
    description: string,
    tag: string,
    ipv4: string,
    ipv6: string,
}

export struct ProviderRow {
    id: string,
    name: string,
    symbol: string,
    ipv4: string,
    ipv6: string,
    summary: string,
    pros: string,
    cons: string,
    custom: bool,
    active: bool,
    tag: string,
    profile_count: int,
}

export struct SpeedSample {
    download: float,
    upload: float,
}
